print("Hello Welcome")
print("How are u")
print("Welcome to Google Cloud Platform")
print("Welcome to the Zeal College of engineering ")
print("This is the Computer Department present in D building ")
